name: "Test and Release HuggingFace Binary"
on:
    workflow_dispatch:

jobs:
    test_and_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: goto-bus-stop/setup-zig@v2
              with:
                version: 0.13.0
            - run: zig build test
            - run: zig build --release=fast

            - uses: actions/upload-artifact@v4
              with:
                name: hf_hub
                path: zig-out/bin/hf_hub

